services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - type: volume
        source: public-assets
        target: /app/public
        read_only: false
      - type: volume
        source: static-assets
        target: /app/.next/static
        read_only: false
    network_mode: "host"
    develop:
      watch:
        - action: sync
          path: /frontend
          target: /app
        - action: rebuild
          path: /frontend/package.json
  backend:
    build:
      context: ./backend
    volumes_from:
      - frontend:ro
    network_mode: "host"
    develop:
      watch:
        - action: sync+restart
          path: /backend
          target: /backend

volumes:
  public-assets:
   external: false
  static-assets:
    external: false
